import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/header";
import Footer from "./header/footer";
import { Stack } from "@mui/material";
import SideBar from "./header/sideBar";
import Divider from '@mui/material/Divider';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ height: '100vh'}}
      >
        <Header />
        <Stack direction='row' padding='20px' gap='30px'>
          <Stack style={{ position: 'sticky', top: '0px'}}><SideBar /></Stack>
          <Divider orientation="vertical" flexItem />
          <Stack>{children}</Stack>
        </Stack>
        <Footer />
      </body>
    </html>
  );
}
